import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Building2,ClipboardCheck,AlertTriangle,CalendarDays,Plus,Search,Settings,FileText,Activity,ChevronRight,Menu,X,LayoutDashboard,Boxes,Link2,Brain,ShieldCheck} from 'lucide-react';
import './styles.css';

const seedAssets=[
 {id:'ATV-0001',name:'Edifício Rua Central',type:'Edifício multifamiliar',location:'Porto',status:'Ativo',ec:2,maintenance:'Bom',components:12,pathologies:4},
 {id:'ATV-0002',name:'Edifício Avenida da República',type:'Edifício multifamiliar',location:'Vila Nova de Gaia',status:'Ativo',ec:1,maintenance:'Razoável',components:8,pathologies:2}
];
const seedInspections=[
 {id:'INS-0001',asset:'ATV-0001',type:'Principal',date:'2026-10-02',inspector:'Jorge Maçães',ec:2,maintenance:'Bom',pathologies:3},
 {id:'INS-0002',asset:'ATV-0001',type:'Rotina',date:'2026-09-15',inspector:'Jorge Maçães',ec:null,maintenance:'Bom',pathologies:1}
];
const seedPathologies=[
 {id:'PAT-0001',asset:'ATV-0001',subcomponent:'Fachada Norte',material:'Betão',type:'Fissuração',characteristic:'Diagonal',cause:'Movimentos diferenciais',effect:'Entrada de água',work:'Selagem de fissuras',unit:'m',status:'Identificada',ec:3},
 {id:'PAT-0002',asset:'ATV-0001',subcomponent:'Fachada Norte',material:'Betão armado',type:'Corrosão',characteristic:'Armaduras expostas',cause:'Carbonatação',effect:'Deterioração das armaduras',work:'Reparação de betão em profundidade',unit:'m²',status:'Em análise',ec:4}
];
const seedMaterials=['Betão','Betão armado','Aço','Alumínio','Madeira','Cerâmica'];
const seedRelations=[
 {id:'REL-001',pathology:'Fissuração',characteristic:'Diagonal',material:'Betão',cause:'Movimentos diferenciais',effect:'Entrada de água',work:'Selagem de fissuras',unit:'m',confidence:'Confirmada'},
 {id:'REL-002',pathology:'Corrosão',characteristic:'Armaduras expostas',material:'Betão armado',cause:'Carbonatação',effect:'Deterioração das armaduras',work:'Reparação de betão em profundidade',unit:'m²',confidence:'Confirmada'}
];
function load(k,s){try{return JSON.parse(localStorage.getItem(k))||s}catch{return s}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v));return v}

function App(){
 const [assets,setAssets]=useState(()=>load('ativus_assets',seedAssets));
 const [inspections,setInspections]=useState(()=>load('ativus_inspections',seedInspections));
 const [pathologies,setPathologies]=useState(()=>load('ativus_pathologies',seedPathologies));
 const [materials,setMaterials]=useState(()=>load('ativus_materials',seedMaterials));
 const [relations,setRelations]=useState(()=>load('ativus_relations',seedRelations));
 const [view,setView]=useState('dashboard'),[selected,setSelected]=useState(null),[menu,setMenu]=useState(false),[query,setQuery]=useState('');
 const [paramTab,setParamTab]=useState('relations');
 const filtered=useMemo(()=>assets.filter(a=>(a.name+' '+a.location+' '+a.id).toLowerCase().includes(query.toLowerCase())),[assets,query]);
 const current=selected?assets.find(a=>a.id===selected):null;
 const nav=[['dashboard','Dashboard',LayoutDashboard],['assets','Ativos / Inventário',Building2],['inspections','Inspeções',ClipboardCheck],['pathologies','Patologias',AlertTriangle],['agenda','Agenda',CalendarDays],['monitoring','Sistemas de Monitorização',Activity],['documents','Documentação',FileText],['settings','Parametrização',Settings]];
 const go=id=>{setView(id);setMenu(false);if(id!=='asset')setSelected(null)};
 const addAsset=()=>{const name=window.prompt('Nome do ativo:');if(!name||!name.trim())return;const n=Math.max(0,...assets.map(a=>Number(String(a.id).replace(/\\D/g,''))||0))+1,a={id:'ATV-'+String(n).padStart(4,'0'),name:name.trim(),type:'Edifício residencial',location:'Por definir',status:'Ativo',ec:0,maintenance:'Bom',components:0,pathologies:0};const next=[a,...assets];setAssets(save('ativus_assets',next));setSelected(a.id);setView('asset')};
 const addInspection=asset=>{const n=inspections.length+1,i={id:'INS-'+String(n).padStart(4,'0'),asset,type:'Rotina',date:new Date().toISOString().slice(0,10),inspector:'Utilizador atual',ec:null,maintenance:'Bom',pathologies:0};setInspections(save('ativus_inspections',[i,...inspections]))};
 const addPathology=()=>{const n=pathologies.length+1,p={id:'PAT-'+String(n).padStart(4,'0'),asset:current?.id||assets[0]?.id||'ATV-0001',subcomponent:'Novo subcomponente',material:materials[0]||'Betão',type:'Fissuração',characteristic:'Diagonal',cause:'',effect:'',work:'',unit:'m',status:'Identificada',ec:3};setPathologies(save('ativus_pathologies',[p,...pathologies]));setView('pathologies')};
 return <div className="app">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">7M</div><div><strong>Seven M</strong><span>ATIVUS</span></div><button className="close" onClick={()=>setMenu(false)}><X size={20}/></button></div>
   <nav>{nav.map(([id,label,Icon])=><button className={view===id?'nav active':'nav'} key={id} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span></button>)}</nav>
   <div className="sidefoot">MVP 0.2<br/><small>Inventário · inspeção · patologias · parametrização</small></div>
  </aside>
  <main className="main"><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><div className="eyebrow">SEVEN M ATIVUS</div><h1>{view==='dashboard'?'Dashboard':view==='assets'?'Ativos / Inventário':view==='asset'?current?.name||'Ativo':nav.find(x=>x[0]===view)?.[1]||'Ativus'}</h1></div><div className="header-actions"><div className="sync">● Dados locais</div><div className="user">JM</div></div></header>
   {view==='dashboard'&&<Dashboard assets={assets} inspections={inspections} pathologies={pathologies} onAssets={()=>go('assets')} onNew={addAsset}/>}
   {view==='assets'&&<Assets assets={filtered} query={query} setQuery={setQuery} onNew={addAsset} onOpen={id=>{setSelected(id);setView('asset')}}/>}
   {view==='asset'&&current&&<AssetDetail asset={current} inspections={inspections} pathologies={pathologies} onBack={()=>go('assets')} onNewInspection={()=>addInspection(current.id)} onNewPathology={addPathology}/>}
   {view==='inspections'&&<Inspections inspections={inspections} assets={assets}/>}
   {view==='pathologies'&&<Pathologies pathologies={pathologies} assets={assets} onNew={addPathology}/>}
   {view==='agenda'&&<Agenda inspections={inspections} pathologies={pathologies}/>}
   {view==='monitoring'&&<Module icon={Activity} title="Sistemas de Monitorização" text="Instrumentação e aquisição de dados para deslocamentos, velocidade de corrosão e outros sensores."/>}
   {view==='documents'&&<Module icon={FileText} title="Documentação" text="Documentos associados a ativos, componentes, inspeções e intervenções."/>}
   {view==='settings'&&<Parametrization materials={materials} setMaterials={v=>setMaterials(save('ativus_materials',v))} relations={relations} tab={paramTab} setTab={setParamTab}/>}
  </main>
 </div>
}
function Dashboard({assets,inspections,pathologies,onAssets,onNew}){const ec5=assets.filter(a=>a.ec===5).length,open=pathologies.filter(p=>!['Encerrada','Verificada'].includes(p.status)).length;return <section className="content">
 <div className="hero"><div><span className="pill">MVP 0.2 • Operacional</span><h2>Gestão técnica dos teus ativos</h2><p>Inventário, inspeções, patologias, trabalhos e parametrização num único fluxo.</p></div><button className="primary" onClick={onNew}><Plus size={18}/> Novo Ativo</button></div>
 <div className="stats"><Stat icon={Building2} label="Ativos" value={assets.length}/><Stat icon={ClipboardCheck} label="Inspeções" value={inspections.length}/><Stat icon={AlertTriangle} label="Patologias abertas" value={open}/><Stat icon={ShieldCheck} label="EC 5 / críticos" value={ec5}/></div>
 <div className="grid2"><div className="panel"><div className="panelhead"><div><h3>Ativos recentes</h3><span>Resumo do inventário</span></div><button className="textbtn" onClick={onAssets}>Ver todos <ChevronRight size={16}/></button></div>{assets.slice(0,5).map(a=><AssetRow key={a.id} a={a} onClick={onAssets}/>)}</div>
 <div className="panel"><div className="panelhead"><div><h3>Últimas inspeções</h3><span>Atividade recente</span></div></div>{inspections.slice(0,5).map(i=><div className="inspectionrow" key={i.id}><div className="datebox">{i.date.slice(8,10)}<small>{i.date.slice(5,7)}</small></div><div><strong>{i.type}</strong><span>{i.asset} · {i.inspector}</span></div><Badge value={i.maintenance}/></div>)}</div></div>
 </section>}
function Stat({icon:Icon,label,value}){return <div className="stat"><div className="staticon"><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Assets({assets,query,setQuery,onNew,onOpen}){return <section className="content"><div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar ativo, local ou código..."/></div><button className="primary" onClick={onNew}><Plus size={18}/> Novo Ativo</button></div><div className="table panel"><div className="thead"><span>Ativo</span><span>Localização</span><span>EC</span><span>Manutenção</span><span>Estado</span><span></span></div>{assets.map(a=><button className="trow" key={a.id} onClick={()=>onOpen(a.id)}><div><strong>{a.name}</strong><small>{a.id} · {a.type}</small></div><span>{a.location}</span><span><Ec value={a.ec}/></span><span><Badge value={a.maintenance}/></span><span className="green">● {a.status}</span><ChevronRight size={18}/></button>)}</div></section>}
function AssetDetail({asset,inspections,pathologies,onBack,onNewInspection,onNewPathology}){const list=inspections.filter(i=>i.asset===asset.id),pats=pathologies.filter(p=>p.asset===asset.id);return <section className="content"><button className="back" onClick={onBack}>← Voltar aos ativos</button><div className="assethead"><div><span className="pill">{asset.id}</span><h2>{asset.name}</h2><p>{asset.type} · {asset.location}</p></div><div className="actions"><button className="secondary" onClick={onNewPathology}><Plus size={16}/> Patologia</button><button className="primary" onClick={onNewInspection}><Plus size={18}/> Nova inspeção</button></div></div><div className="stats compact"><Stat icon={Boxes} label="Componentes" value={asset.components}/><Stat icon={AlertTriangle} label="Patologias" value={pats.length}/><Stat icon={ClipboardCheck} label="Inspeções" value={list.length}/><Stat icon={ShieldCheck} label="Estado de conservação" value={'EC '+asset.ec}/></div><div className="grid2"><div className="panel"><h3>Inventário</h3><div className="details"><p><b>Código:</b> {asset.id}</p><p><b>Tipo:</b> {asset.type}</p><p><b>Localização:</b> {asset.location}</p><p><b>Manutenção:</b> <Badge value={asset.maintenance}/></p><p><b>EC:</b> <Ec value={asset.ec}/></p></div></div><div className="panel"><h3>Patologias recentes</h3>{pats.length?pats.map(p=><div className="listrow" key={p.id}><div><strong>{p.type} · {p.characteristic}</strong><span>{p.material} · {p.location||p.subcomponent}</span></div><Ec value={p.ec}/></div>):<p className="empty">Ainda não existem patologias.</p>}</div></div></section>}
function Inspections({inspections,assets}){return <section className="content"><div className="panel table"><div className="thead"><span>Inspeção</span><span>Ativo</span><span>Data</span><span>Tipo</span><span>Manutenção</span><span>Patologias</span></div>{inspections.map(i=><div className="trow" key={i.id}><div><strong>{i.id}</strong><small>{i.inspector}</small></div><span>{assets.find(a=>a.id===i.asset)?.name||i.asset}</span><span>{i.date}</span><span>{i.type}</span><span><Badge value={i.maintenance}/></span><span>{i.pathologies}</span></div>)}</div></section>}
function Pathologies({pathologies,assets,onNew}){return <section className="content"><div className="toolbar"><div><h2 className="sectiontitle">Patologias</h2><p className="muted">Causa → Patologia → Efeito → Trabalho</p></div><button className="primary" onClick={onNew}><Plus size={18}/> Nova patologia</button></div><div className="cards">{pathologies.map(p=><div className="pathcard panel" key={p.id}><div className="pathhead"><div><span className="pill">{p.id}</span><h3>{p.type} <small>· {p.characteristic}</small></h3></div><Ec value={p.ec}/></div><div className="chain"><span>{p.material}</span><ChevronRight/><span>{p.cause||'Causa por determinar'}</span><ChevronRight/><span>{p.effect||'Efeito por determinar'}</span><ChevronRight/><span>{p.work||'Trabalho por determinar'}</span></div><div className="pathfoot"><span>{assets.find(a=>a.id===p.asset)?.name||p.asset} · {p.subcomponent}</span><Badge value={p.status}/></div></div>)}</div></section>}
function Agenda({inspections,pathologies}){return <section className="content"><div className="grid2"><div className="panel"><h3>Próximas inspeções</h3>{inspections.slice(0,8).map(i=><div className="listrow" key={i.id}><div><strong>{i.date} · {i.type}</strong><span>{i.asset} · {i.inspector}</span></div><ClipboardCheck size={18}/></div>)}</div><div className="panel"><h3>Prazos de intervenção</h3>{pathologies.filter(p=>p.ec>=4).map(p=><div className="listrow" key={p.id}><div><strong>{p.id} · {p.type}</strong><span>{p.ec===5?'Intervenção imediata':'Resolver até 1 ano'}</span></div><Ec value={p.ec}/></div>)}</div></div></section>}
function Parametrization({materials,setMaterials,relations,tab,setTab}){const tabs=[['relations','Relações técnicas',Link2],['materials','Materiais',Boxes],['rules','Regras / Comportamentos',Settings],['ai','IA / Aprendizagem',Brain]];const addMaterial=()=>{const n=prompt('Novo material');if(n&&n.trim()&&!materials.includes(n.trim()))setMaterials([...materials,n.trim()])};return <section className="content"><div className="paramnav">{tabs.map(([id,label,Icon])=><button className={tab===id?'paramactive':''} onClick={()=>setTab(id)} key={id}><Icon size={17}/>{label}</button>)}</div>{tab==='relations'&&<div className="panel"><div className="panelhead"><div><h3>Relações técnicas</h3><span>Material → Patologia → Causa → Efeito → Trabalho → Unidade</span></div><span className="pill">{relations.length} relações</span></div><div className="relationtable">{relations.map(r=><div className="relation" key={r.id}><b>{r.pathology}</b><span>{r.characteristic}</span><span>{r.material}</span><span>{r.cause}</span><span>{r.effect}</span><span>{r.work}</span><span>{r.unit}</span><Badge value={r.confidence}/></div>)}</div></div>}{tab==='materials'&&<div className="panel"><div className="panelhead"><div><h3>Materiais</h3><span>Usados no inventário dos subcomponentes e na compatibilidade de patologias.</span></div><button className="primary" onClick={addMaterial}><Plus size={17}/> Material</button></div><div className="chips">{materials.map(m=><span className="chip" key={m}>{m}</span>)}</div></div>}{tab==='rules'&&<div className="panel"><h3>Regras / Comportamentos</h3><div className="rule"><b>SE</b> patologia com <strong>EC 5</strong> <b>ENTÃO</b> intervenção imediata + alerta + restrição de acesso/sinalização.</div><div className="rule"><b>SE</b> componente <strong>EC 4</strong> <b>ENTÃO</b> prazo máximo configurado de 1 ano.</div><div className="rule"><b>EC componente</b> = maior EC dos subcomponentes; apresentar também mínimo, média e distribuição.</div></div>}{tab==='ai'&&<div className="panel ai"><Brain size={38}/><h3>IA baseada na parametrização e histórico</h3><p>As relações confirmadas pelo inspetor alimentam sugestões futuras. Cada sugestão deve apresentar confiança e permitir aceitar, editar ou rejeitar.</p><div className="airow"><span>Fissuração + diagonal + Betão</span><strong>→ Movimentos diferenciais</strong><em>92%</em></div><div className="airow"><span>Corrosão + Betão armado</span><strong>→ Carbonatação</strong><em>89%</em></div></div>}</section>}
function Module({icon:Icon,title,text}){return <section className="content"><div className="placeholder panel"><Icon size={40}/><h2>{title}</h2><p>{text}</p><span className="pill">Módulo base integrado</span></div></section>}
function AssetRow({a,onClick}){return <button className="assetrow" onClick={onClick}><div className="assetavatar"><Building2 size={19}/></div><div><strong>{a.name}</strong><span>{a.id} · {a.location}</span></div><Ec value={a.ec}/><ChevronRight size={17}/></button>}
function Ec({value}){return <span className={'ec ec'+value}>EC {value}</span>}
function Badge({value}){return <span className={'badge '+String(value).toLowerCase().replaceAll(' ','-')}>{value}</span>}
createRoot(document.getElementById('root')).render(<App/>);